In [1]:
import torch

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
x.shape

torch.Size([12])

In [5]:
# 返回元素的总数
x.numel()

12

In [6]:
x.reshape(3, 4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [7]:
x.reshape(-1, 2)

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]])

In [8]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [10]:
torch.randn(3, 4)

tensor([[ 0.0063, -0.8724, -0.5254,  0.5407],
        [ 1.5339, -1.9719,  0.7848, -0.0415],
        [-0.7134,  2.1212, -1.0452, -0.4233]])

In [11]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [20]:
x = torch.tensor([1.0, 3, 4, 8])
y = torch.tensor([3, 2, 2, 2])
x + y

tensor([ 4.,  5.,  6., 10.])

In [21]:
x - y

tensor([-2.,  1.,  2.,  6.])

In [22]:
x * y

tensor([ 3.,  6.,  8., 16.])

In [23]:
x / y

tensor([0.3333, 1.5000, 2.0000, 4.0000])

In [24]:
x ** y

tensor([ 1.,  9., 16., 64.])

In [25]:
torch.exp(x)

tensor([2.7183e+00, 2.0086e+01, 5.4598e+01, 2.9810e+03])

In [26]:
x = torch.arange(12, dtype=torch.float32).reshape((3, 4))
y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((x, y), dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [27]:
torch.cat((x, y), dim=1)

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [28]:
x == y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [29]:
x.sum()

tensor(66.)

In [30]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a

tensor([[0],
        [1],
        [2]])

In [31]:
b

tensor([[0, 1]])

In [32]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [36]:
print(x[-1], x[1:3], sep='\n')

tensor([ 8.,  9., 10., 11.])
tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


In [37]:
x[0:2, :] = 12
x

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [38]:
before = id(y)
before

1621148157568

In [39]:
y = y + x
id(y)

1621148063200

In [40]:
before == id(y)

False

In [41]:
# 用+=不会改变内存,原地操作
medium = id(y)
y += x
medium == id(y)

True

In [42]:
A = x.numpy()
B = torch.tensor(A)
print(type(A), '\n', type(B))

<class 'numpy.ndarray'> 
 <class 'torch.Tensor'>


In [43]:
#练习
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [44]:
# 运行本节中的代码。将本节中的条件语句X == Y更改为X < Y或X > Y，然后看看你可以得到什么样的张量。
X < Y, X > Y

(tensor([[ True, False,  True, False],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[False, False, False, False],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]]))

In [53]:
# 用其他形状（例如三维张量）替换广播机制中按元素操作的两个张量。结果是否与预期相同？
a = torch.arange(6).reshape((3, 1, 2))
b = torch.arange(6).reshape((3, 2, 1))
a, b

(tensor([[[0, 1]],
 
         [[2, 3]],
 
         [[4, 5]]]),
 tensor([[[0],
          [1]],
 
         [[2],
          [3]],
 
         [[4],
          [5]]]))

In [54]:
a + b

tensor([[[ 0,  1],
         [ 1,  2]],

        [[ 4,  5],
         [ 5,  6]],

        [[ 8,  9],
         [ 9, 10]]])

In [55]:
(a+b).shape

torch.Size([3, 2, 2])